// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grjuhcdtnmucqqpqukpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyanVoY2R0bm11Y3FxcHF1a3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTM0NzMsImV4cCI6MjA2NTQ2OTQ3M30.2qD8ygV4UvCgBkkuPHMs3O1Iyk_jP0e0SmngXA64p1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);